FROM golang:1.20.4

WORKDIR /app

COPY go.mod go.sum ./client/client.go ./

RUN go mod download
RUN GO_ENABLED=0 GOOS=linux go build -o client client.go
RUN ["chmod", "+x", "./client"]

#FROM scratch
#COPY --from=builder /app/client ./

CMD ["./client"]