FROM golang:1.20.4

WORKDIR /app

COPY go.mod go.sum ./server/server.go ./

RUN go mod download
RUN GO_ENABLED=0 GOOS=linux go build -o server server.go
RUN apt-get update && apt-get install sqlite3 -y
RUN ["chmod", "+x", "./server"]
RUN mkdir database

#FROM scratch
#COPY --from=builder /app/server ./

CMD [ "./server" ]